// nextjs-demo/components/PostCreate.tsx
import { useState } from 'react';
import { useApiSubmit } from '@/hooks/useApi';
import { postsApi } from '@/lib/api';

interface PostCreateProps {
  onPostCreated?: () => void;
}

export default function PostCreate({ onPostCreated }: PostCreateProps) {
  const [title, setTitle] = useState('');
  const { submit, loading, error } = useApiSubmit();

  const onSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    
    if (!title.trim()) {
      return;
    }

    await submit(
      () => postsApi.createPost({ title: title.trim() }),
      () => {
        setTitle('');
        if (onPostCreated) onPostCreated();
      }
    );
  };

  return (
    <div className="enhanced-form">
      <form onSubmit={onSubmit}>
        <div className="form-group">
          <label className="form-label">📝 Post Title</label>
          <input
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="form-control"
            placeholder="What's on your mind?"
            disabled={loading}
            required
          />
        </div>
        {error && (
          <div style={{ color: '#e53e3e', marginBottom: '10px', fontSize: '0.9rem' }}>
            ❌ Error: {error}
          </div>
        )}
        <button 
          className="btn btn-primary" 
          type="submit"
          disabled={loading || !title.trim()}
        >
          {loading ? '⏳ Publishing...' : '🚀 Publish Post'}
        </button>
      </form>
    </div>
  );
}

// angular_client/src/app/components/post-create/post-create.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { PostService } from '../../services/post.service';
import { CreatePostRequest } from '../../models/post.model';

@Component({
  selector: 'app-post-create',
  templateUrl: './post-create.component.html',
  styleUrls: ['./post-create.component.css']
})
export class PostCreateComponent {
  @Output() postCreated = new EventEmitter<void>();
  
  postForm: FormGroup;
  loading = false;
  error: string | null = null;

  constructor(
    private fb: FormBuilder,
    private postService: PostService
  ) {
    this.postForm = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(1)]]
    });
  }

  get title() {
    return this.postForm.get('title');
  }

  onSubmit(): void {
    if (this.postForm.valid && !this.loading) {
      const title = this.title?.value?.trim();
      if (!title) return;

      this.loading = true;
      this.error = null;

      const postData: CreatePostRequest = { title };

      this.postService.createPost(postData).subscribe({
        next: () => {
          this.postForm.reset();
          this.loading = false;
          this.postCreated.emit();
        },
        error: (error) => {
          this.error = error.message || 'An error occurred';
          this.loading = false;
        }
      });
    }
  }

  get isSubmitDisabled(): boolean {
    return this.loading || !this.title?.value?.trim();
  }
}
<div class="enhanced-form">
  <form [formGroup]="postForm" (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label class="form-label">📝 Post Title</label>
      <input
        formControlName="title"
        class="form-control"
        placeholder="What's on your mind?"
        [disabled]="loading"
        required>
    </div>
    
    <div *ngIf="error" class="error-message">
      ❌ Error: {{ error }}
    </div>
    
    <button 
      class="btn btn-primary" 
      type="submit"
      [disabled]="isSubmitDisabled">
      {{ loading ? '⏳ Publishing...' : '🚀 Publish Post' }}
    </button>
  </form>
</div>
