// angular_client/src/app/components/comment-create/comment-create.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CommentService } from '../../services/comment.service';
import { CreateCommentRequest } from '../../models/comment.model';

@Component({
  selector: 'app-comment-create',
  templateUrl: './comment-create.component.html',
  styleUrls: ['./comment-create.component.css']
})
export class CommentCreateComponent {
  @Input() postId!: string;
  @Output() commentAdded = new EventEmitter<void>();
  
  commentForm: FormGroup;
  loading = false;
  error: string | null = null;

  constructor(
    private fb: FormBuilder,
    private commentService: CommentService
  ) {
    this.commentForm = this.fb.group({
      content: ['', [Validators.required, Validators.minLength(1)]]
    });
  }

  get content() {
    return this.commentForm.get('content');
  }

  onSubmit(): void {
    if (this.commentForm.valid && !this.loading) {
      const content = this.content?.value?.trim();
      if (!content) return;

      this.loading = true;
      this.error = null;

      const commentData: CreateCommentRequest = { content };

      this.commentService.createComment(this.postId, commentData).subscribe({
        next: () => {
          this.commentForm.reset();
          this.loading = false;
          this.commentAdded.emit();
        },
        error: (error) => {
          this.error = error.message || 'An error occurred';
          this.loading = false;
        }
      });
    }
  }

  get isSubmitDisabled(): boolean {
    return this.loading || !this.content?.value?.trim();
  }
}
<div class="comment-form">
  <form [formGroup]="commentForm" (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label class="form-label">✍️ Add a comment</label>
      <input
        formControlName="content"
        class="form-control"
        placeholder="Share your thoughts..."
        [disabled]="loading"
        required>
    </div>
    
    <div *ngIf="error" class="error-message">
      ❌ Error: {{ error }}
    </div>
    
    <button 
      class="btn btn-primary" 
      type="submit"
      [disabled]="isSubmitDisabled">
      {{ loading ? '⏳ Posting...' : '💭 Post Comment' }}
    </button>
  </form>
</div>

// nextjs-demo/components/CommentCreate.tsx
import { useState } from 'react';
import { useApiSubmit } from '@/hooks/useApi';
import { commentsApi } from '@/lib/api';

interface CommentCreateProps {
  postId: string;
  onCommentAdded?: () => void;
}

export default function CommentCreate({ postId, onCommentAdded }: CommentCreateProps) {
  const [content, setContent] = useState('');
  const { submit, loading, error } = useApiSubmit();

  const onSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    
    if (!content.trim()) {
      return;
    }

    await submit(
      () => commentsApi.createComment(postId, { content: content.trim() }),
      () => {
        setContent('');
        if (onCommentAdded) onCommentAdded();
      }
    );
  };

  return (
    <div className="comment-form">
      <form onSubmit={onSubmit}>
        <div className="form-group">
          <label className="form-label">✍️ Add a comment</label>
          <input
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="form-control"
            placeholder="Share your thoughts..."
            disabled={loading}
            required
          />
        </div>
        {error && (
          <div style={{ color: '#e53e3e', marginBottom: '10px', fontSize: '0.9rem' }}>
            ❌ Error: {error}
          </div>
        )}
        <button 
          className="btn btn-primary" 
          type="submit"
          disabled={loading || !content.trim()}
        >
          {loading ? '⏳ Posting...' : '💭 Post Comment'}
        </button>
      </form>
    </div>
  );
}
